dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=okex setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: fyjvgFJLokfGcAEtuzTLlrXIuaw7xjTgNRXRA6G69bAQKkEy7uDa/ZPL2UzsTHOfGvNA4mjWZrHlqpiqRgSIKC/aZT6ZjvmOgsrcViWp5kfncXxd/MFxuD3hckaRPoihuh5uY2r+R1ovDdfFaZWbRlTv8yKWzbcfp5YvYgbslIAV0UnuhNf5LCfoVnv0U8xIwkGXMYiO01IdmgjkZduwQ8ao+Js+CPGabEvyBRG6WGZnc9m7W+ZtiKi70J9T0x345l/lx8SqxWeONJChR04A7TrohzK81Xc4GJSpUa0X+YAd0CRTTFa7zeY/57s74nlWqNBxMWuXrxpwkfoh/HQqV47mKVcB8gRdw35uQLdv8WGmub1J94uPUS3ucOQyYqY6TP8WCEJyvy/4W/CaqV0SH9G2v/1IPsAzhywVYhEKaVp58Ldp8OhzthprsRUdyuFYKHLR5t9+ggmX3BV7C2r/KSEGtdAFoxSmKQoreo+Abdb3X8X4Fjs9AHqYoYdl7mHXUyY1E2ezNAp96FjcQyNS9zYMGeOTfKOccpzlzFgeqhy3BJ+o7Q/dQZPsssHqb0A90LMoY5F4FrlFk7qrw4v+ZTNpd2L8MCtAURj7v3/pm/jP9Dh6QzEwu7sG6PurOmCKv0+wxBXFRqj+loAIYVScNzJSkeuTWNE4rd8+2yOCvSg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
