sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=okex setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: fMDh8Jsek1ZfsfoXA2mMTEjh1BS0A9uefmtybyZmbgxXRDq/WjZxFcEAbd15B4H86h4SQLWkhBMk6LJHYk31yd1xIJdLxnIWRWaANnz1lLjLKazYVbg0rV1aNwTI+Jqd/ykLZdg/SngDQa1YeCWYGtO4xD9/sTBbaOd61z5nR8FbZZhvfYhdSl0aGHjps9b5mvgKfQC4C1tY5K9ybFBxBQQu0dOsIUTT+8mqCakFkKFXs3Wj0M189qV913tzcbCdwFj+r7x6pNKQINRAbOU7/dlP9DGr1pXtFBaRxdWfoZ0LGCbKfLZpcVtN+6hfsymnUD4lNFhFWxFiHgn0Kr6AZYN0qRu8bc+hJ+vfmG4By/pdRbZ65BBL+LI5Q7snLdWLf45exKThEljp30u8zNOYrTvR7p4hKJX6W9e7wj8Kb3NPVSE8CcXqkNYpjZLvRiqVYkyBbnunbiF5NeSRvNNPQtZ3Y2mS9bqibrtIMFKlaCrjtux97FtYlsxB1DVJKNAtjNADErE170Cch8MbRaFvTeWUSNAcGcg1SJ44uPoU3URvg+7bXcrEgFP9KnGQIq5Rtms3H/b9ZFIBKmmM22UorgADbnK59X7otYn1kfAXV0KsI+NRYlh2lcTj5PqJJ6JyygydmO0SAlnPNWEDYQfWYliNv/qvN6auRuWZUGX8Y60=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
